<div id="idTopLine">
    <ul class="ul-option-menu">
        <li><a href="/users/">Пользователи</a></li>
        <li><a href="/projects/edit/">Создать проект</a></li>
    </ul>
</div>
<div id="idBody">
    <div class="cnt">
        <div class="task-list">
            <h1>Список проектов</h1>
            <br/>
            <table class="t-task-list">
                <thead>
                <tr>
                    <th width="50%">Название</th>
                    <th width="10%">Менеджер</th>
                    <th width="10%">Всего</th>
                    <th width="15%">Не выполнено</th>
                    <th width="15%">Действия</th>
                </tr>
                </thead>
                <tbody>
                <?php if (count($this->projects)) { ?>
                    <?php foreach ($this->projects as $p) { ?>
                        <tr>
                            <td>
                                <a href="/tasks/index/project_id/<?php echo $p->getId() ?>"><?php echo $p->getTitle() ?></a>
                            </td>
                            <td><?php echo $p->getManagerLogin() ?></td>
                            <td><?php echo $p->getTotalTasks() ?></td>
                            <td><?php echo $p->getNotComplete() ?></td>
                            <td>
                                <a href="/projects/edit/id/<?php echo $p->getId() ?>/">Редактировать</a> |
                                <a href="/projects/drop/id/<?php echo $p->getId() ?>/" class="drop-project">Удалить</a>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="4" style="text-align: center;">Нет проектов</td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('.drop-project').click(function (e) {
        e.preventDefault();
        if (confirm('Удалить проект и все связанны с ним задачи?')) {
            window.location.href = $(this).attr('href');
        }
    });
</script>
