<div id="idTopLine">
    <ul class="ul-main-menu">
        <li><a href="/users/">Список пользователей</a></li>
        <li><a href="/users/edit/">Создать пользователя</a></li>
    </ul>
</div>
<div id="idBody">
    <div class="cnt">
        <div class="task-create">
            <h1>Редактирование пользователя</h1>
            <br/>

            <div class="form">
                <?php echo $this->form ?>
            </div>
            <br/>
        </div>
    </div>
</div>