<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        mode: "textareas",
        theme: "advanced",
        theme_advanced_buttons1: "code,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,bullist,numlist,undo,redo,link,unlink",
        theme_advanced_buttons2: "",
        theme_advanced_buttons3: "",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left"
    });
</script>
<?php
$projectSuffix = $this->projectId
    ? sprintf('project_id/%d/', $this->projectId)
    : '';
?>
<div id="idTopLine">
    <ul class="ul-main-menu">
        <li><a href="/tasks/index/<?php echo $projectSuffix ?>">Все задания</a></li>
        <li><a href="/tasks/index/filter/new/<?php echo $projectSuffix ?>">Новые</a></li>
        <li><a href="/tasks/index/filter/processing/<?php echo $projectSuffix ?>">Выполняются</a></li>
        <li><a href="/tasks/index/filter/waiting/<?php echo $projectSuffix ?>">Приостановленные</a></li>
        <li><a href="/tasks/index/filter/completed/<?php echo $projectSuffix ?>">Выполненные</a></li>
    </ul>
</div>
<div id="idBody">
    <div class="cnt">
        <div class="task-create">
            <h1>Редактирование задачи</h1>
            <br/>

            <div class="form">
                <?php echo $this->form ?>
            </div>
            <br/>
        </div>
    </div>
</div>