<?php
$projectSuffix = $this->project
    ? sprintf('project_id/%d/', $this->project->getId())
    : '';
?>
<div id="idTopLine">
    <ul class="ul-option-menu">
        <li><a href="/projects/">Вернуться к проектам</a></li>
        <li><a href="/tasks/edit/<?php echo $projectSuffix ?>">Создать задачу</a></li>
    </ul>
    <ul class="ul-main-menu">
        <li><a href="/tasks/index/filter/all/assigned/<?php echo $this->assigned ?>/<?php echo $projectSuffix ?>">Все
                задания</a></li>
        <li>
            <a href="/tasks/index/filter/new/assigned/<?php echo $this->assigned ?>/<?php echo $projectSuffix ?>">Новые</a>
        </li>
        <li>
            <a href="/tasks/index/filter/processing/assigned/<?php echo $this->assigned ?>/<?php echo $projectSuffix ?>">Выполняются</a>
        </li>
        <li><a href="/tasks/index/filter/waiting/assigned/<?php echo $this->assigned ?>/<?php echo $projectSuffix ?>">Приостановленные</a>
        </li>
        <li><a href="/tasks/index/filter/completed/assigned/<?php echo $this->assigned ?>/<?php echo $projectSuffix ?>">Выполненные</a>
        </li>
    </ul>
</div>
<div id="idBody">
    <div class="cnt">
        <?php if ($this->project) { ?>
            <h1><?php echo $this->project->getTitle() ?></h1>
        <?php } ?>
        <div class="task-list">
            <h1>Список заданий</h1>

            <div class="navi-menu">
                <ul class="ul-nav-menu">
                    <li>
                        <a href="/tasks/index/filter/<?php echo $this->filter ?>/assigned/all/<?php echo $projectSuffix ?>">Все
                            задания</a></li>
                    <li>
                        <a href="/tasks/index/filter/<?php echo $this->filter ?>/assigned/me/<?php echo $projectSuffix ?>">Только
                            свои задания</a></li>
                </ul>
            </div>
            <br/>
            <table class="t-task-list">
                <thead>
                <tr>
                    <th width="10%">Тип</th>
                    <th width="5%">Приоритет</th>
                    <th width="40%">Название</th>
                    <th width="25%">Создано</th>
                    <th width="25%">Начато</th>
                    <th width="15%">Обрабатывает</th>
                    <th width="25%">Завершено</th>
                    <th width="15%">Статус</th>
                </tr>
                </thead>
                <tbody>
                <?php if (count($this->tasks)) { ?>
                    <?php foreach ($this->tasks as $t) { ?>
                        <tr>
                            <td><?php echo $t->getTypeTitle() ?></td>
                            <td class="<?php echo $t->getPriority() ?>">
                                <?php echo $t->getPriorityTitle() ?>
                            </td>
                            <td>
                                <a href="/tasks/view/id/<?php echo $t->getId() ?>/">
                                    <?php echo $t->getTitle() ?>
                                </a>
                            </td>
                            <td>
                                <?php echo $t->getCreateDateFormatted() ?> &lt;- <?php echo $t->getCreatedByLogin() ?>
                            </td>
                            <td><?php echo $t->getStartDateFormatted() ?></td>
                            <td><?php echo $t->getAssignedToLogin() ?></td>
                            <td><?php echo $t->getEndDateFormatted() ?></td>
                            <td><?php echo $t->getStatusTitle() ?></td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="8" style="text-align: center;">Нет заданий</td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>