<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        mode: "textareas",
        theme: "advanced",
        theme_advanced_buttons1: "code,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,bullist,numlist,undo,redo,link,unlink",
        theme_advanced_buttons2: "",
        theme_advanced_buttons3: "",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left"
    });
</script>
<div id="idTopLine">
    <ul class="ul-option-menu">
        <li><a href="/tasks/edit/project_id/<?php echo $this->task->getProjectId() ?>/">Создать задание</a></li>
    </ul>
    <ul class="ul-main-menu">
        <li><a href="/tasks/index/project_id/<?php echo $this->task->getProjectId() ?>/">Все задания</a></li>
        <li><a href="/tasks/index/filter/new/project_id/<?php echo $this->task->getProjectId() ?>/">Новые</a></li>
        <li>
            <a href="/tasks/index/filter/processing/project_id/<?php echo $this->task->getProjectId() ?>/">Выполняются</a>
        </li>
        <li>
            <a href="/tasks/index/filter/waiting/project_id/<?php echo $this->task->getProjectId() ?>/">Приостановленные</a>
        </li>
        <li>
            <a href="/tasks/index/filter/completed/project_id/<?php echo $this->task->getProjectId() ?>/">Выполненные</a>
        </li>
    </ul>
</div>
<div id="idBody">
    <div class="cnt">
        <div class="task">
            <span class="task-type"><?php echo $this->task->getTypeTitle() ?> &#8594; </span>

            <h1><?php echo $this->task->getTitle() ?></h1>
            <br/>

            <div class="info">
                <form method="post" action="/tasks/change-status/">
                    <input type="hidden" name="id" value="<?php echo $this->task->getId() ?>"/>
                    <span>
                        <select name="action" id="action">
                            <option value="0">Ваше действие ...</option>
                            <option value="start">Начать</option>
                            <option value="wait">Приостановить</option>
                            <option value="end">Завершить</option>
                        </select>
                    </span> <input type="submit" class="iButton" value="ОК"/>
                </form>
                <ul>
                    <li>Создано: <big><?php echo $this->task->getCreateDateFormatted() ?></big></li>
                    <li>Обрабатывает: <big><?php echo $this->task->getAssignedToLogin() ?></big></li>
                    <li>Начато: <big><?php echo $this->task->getStartDateFormatted() ?></big></li>
                    <li>Завершено: <big><?php echo $this->task->getEndDateFormatted() ?></big></li>
                    <li>Приоритет: <big><?php echo $this->task->getPriorityTitle() ?></big></li>
                    <li>Статус: <big><?php echo $this->task->getStatusTitle() ?></big></li>
                    <li><a href="/tasks/edit/id/<?php echo $this->task->getId() ?>/">Изменить</a></li>
                </ul>
                <br/>
                <?php if ($this->files) { ?>
                    <h2>Приложенные файлы:</h2>
                    <ol>
                        <?php foreach ($this->files as $f) { ?>
                            <li><?php echo $f->getUploadDateFormatted() ?> &mdash; <a
                                    href="/files/<?php echo $f->getFilePath() ?>"><?php echo $f->getFilePath() ?></a>
                            </li>
                        <?php } ?>
                    </ol>
                    <br/>
                <?php } ?>
                <h2>Приложить файлы</h2>
                <?php echo $this->uploadForm ?>
            </div>
            <div class="entry">
                <?php echo $this->task->getText() ?>
            </div>
        </div>
        <?php if (count($this->comments)) { ?>
            <div class="comments">
                <?php foreach ($this->comments as $comment) { ?>
                    <div class="comment">
                        <b><?php echo $comment->getUserLogin() ?></b>: &laquo;<?php echo $comment->getText() ?>&raquo;
                    </div>
                <?php } ?>
            </div>
            <!-- hr /-->
        <?php } ?>
        <div>
            <?php echo $this->commentForm ?>
        </div>
    </div>
</div>