<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>CreoPlanner</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="/style.css" type="text/css" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js"></script>
</head>
<body>
<?php echo $this->layout()->content; ?>
<div id="idFooter">
    <div class="copyright"><span>&copy; 2008&ndash;<?php echo date("Y") ?> by <a href="http://www.creogen.com">Creogen!
                Media Laboratory</a></span></div>
</div>
</body>
</html>